language: java

script:
  - mvn install -DskipTests -Dfindbugs.skip=true -Dpmd.skip=true -Dmaven.javadoc.skip=true

jdk:
  - oraclejdk8
  - openjdk8
dist: trusty

cache:
  directories:
    - $HOME/.m2
