language: java

script:
  - mvn install -DskipTests -Dfindbugs.skip=true -Dpmd.skip=true -Dmaven.javadoc.skip=true

jdk:
  - oraclejdk8
  - openjdk8
dist: trusty

cache:
  directories:
    - $HOME/.m2

deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file: "target/mq-pipeline-notifier.hpi"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
